/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.mpgc.rpg125668;

/*import it.unicam.cs.mpgc.rpg125668.model.characters.Enemy;
import it.unicam.cs.mpgc.rpg125668.model.characters.interfaces.IEnemy;
import it.unicam.cs.mpgc.rpg125668.model.consumable.Book;
import it.unicam.cs.mpgc.rpg125668.model.consumable.Drink;
import it.unicam.cs.mpgc.rpg125668.model.consumable.Snack;
import it.unicam.cs.mpgc.rpg125668.model.dispenser.BookDispenser;
import it.unicam.cs.mpgc.rpg125668.model.dispenser.SnackDrinkDispenser;
import it.unicam.cs.mpgc.rpg125668.model.enumeration.BookRarity;
import it.unicam.cs.mpgc.rpg125668.model.enumeration.EnemyDifficult;
import it.unicam.cs.mpgc.rpg125668.model.enumeration.SkillRarity;
import it.unicam.cs.mpgc.rpg125668.model.enumeration.SkillType;
import it.unicam.cs.mpgc.rpg125668.model.inventory.Inventory;
import it.unicam.cs.mpgc.rpg125668.model.rooms.GameMap;
import it.unicam.cs.mpgc.rpg125668.model.rooms.LootableRoom;
import it.unicam.cs.mpgc.rpg125668.model.rooms.Room;
import it.unicam.cs.mpgc.rpg125668.model.rooms.ShopRoom;
import it.unicam.cs.mpgc.rpg125668.model.rooms.interfaces.IGameMap;
import it.unicam.cs.mpgc.rpg125668.model.rooms.interfaces.IRoom;
import it.unicam.cs.mpgc.rpg125668.model.rooms.interfaces.IRoomLootable;
import it.unicam.cs.mpgc.rpg125668.model.rooms.interfaces.IShopRoom;
import it.unicam.cs.mpgc.rpg125668.model.skill.BossSkill;
import it.unicam.cs.mpgc.rpg125668.model.skill.interfaces.IBossSkill;*/
import it.unicam.cs.mpgc.rpg125668.model.characters.Enemy;
import it.unicam.cs.mpgc.rpg125668.model.characters.Level;
import it.unicam.cs.mpgc.rpg125668.model.characters.Student;
import it.unicam.cs.mpgc.rpg125668.model.characters.interfaces.IStudent;
import it.unicam.cs.mpgc.rpg125668.model.consumable.interfaces.IItem;
import it.unicam.cs.mpgc.rpg125668.model.inventory.Inventory;
import it.unicam.cs.mpgc.rpg125668.model.rooms.interfaces.IRoom;
import it.unicam.cs.mpgc.rpg125668.model.skill.interfaces.IBossSkill;
import it.unicam.cs.mpgc.rpg125668.model.skill.interfaces.IStudentSkill;
import it.unicam.cs.mpgc.rpg125668.persistence.entity.character.EnemyEntity;
import it.unicam.cs.mpgc.rpg125668.persistence.entity.character.StudentEntity;
import it.unicam.cs.mpgc.rpg125668.persistence.entity.item.BookEntity;
import it.unicam.cs.mpgc.rpg125668.persistence.entity.room.RoomEntity;
import it.unicam.cs.mpgc.rpg125668.persistence.entity.skill.BossSkillEntity;
import it.unicam.cs.mpgc.rpg125668.persistence.entity.skill.StudentSkillEntity;
import it.unicam.cs.mpgc.rpg125668.persistence.mapper.*;
import it.unicam.cs.mpgc.rpg125668.persistence.store.character.EnemyStore;
import it.unicam.cs.mpgc.rpg125668.persistence.store.character.StudentStore;
import it.unicam.cs.mpgc.rpg125668.persistence.store.item.ItemStore;
import it.unicam.cs.mpgc.rpg125668.persistence.store.room.RoomStore;
import it.unicam.cs.mpgc.rpg125668.persistence.store.skill.SkillStore;

import java.util.HashMap;
import java.util.List;

public class App {
    public static void main(String[] args) {

        System.out.println("=== TEST PERSISTENZA ===\n");

        // ── 1. TEST CARICAMENTO DATI STATICI ──────────────────

        System.out.println("--- 1. Caricamento skill studente ---");
        SkillStore<StudentSkillEntity> studentSkillStore =
                new SkillStore<>(StudentSkillEntity.class);
        List<StudentSkillEntity> studentSkills = studentSkillStore.findAll();
        studentSkills.forEach(s ->
                System.out.println("  Skill: " + s.getName() + " | Danno: " + s.getDamage() + " | Rarità: " + s.getRarity())
        );

        System.out.println("\n--- 2. Caricamento skill boss ---");
        SkillStore<BossSkillEntity> bossSkillStore =
                new SkillStore<>(BossSkillEntity.class);
        List<BossSkillEntity> bossSkills = bossSkillStore.findAll();
        bossSkills.forEach(s ->
                System.out.println("  Skill: " + s.getName() + " | Danno: " + s.getDamage() + " | Rarità: " + s.getRarity())
        );

        System.out.println("\n--- 3. Caricamento nemici ---");
        EnemyStore enemyStore = new EnemyStore();
        List<EnemyEntity> enemies = enemyStore.findAll();
        enemies.forEach(e ->
                System.out.println("  Nemico: " + e.getName() + " | Difficoltà: " + e.getDifficult() + " | HP: " + e.getLife())
        );

        System.out.println("\n--- 4. Caricamento libri ---");
        ItemStore itemStore = new ItemStore();
        List<BookEntity> books = itemStore.findAllBooks();
        books.forEach(b ->
                System.out.println("  Libro: " + b.getName() + " | Rarità: " + b.getRarity() + " | Prezzo: " + b.getPrice())
        );

        System.out.println("\n--- 5. Caricamento stanze ---");
        RoomStore roomStore = new RoomStore();
        List<RoomEntity> rooms = roomStore.findAll();
        rooms.forEach(r ->
                System.out.println("  Stanza: " + r.getName() + " | Uscite: " + r.getExits().size())
        );

        // ── 2. TEST MAPPER entity → model ─────────────────────

        System.out.println("\n--- 6. Mapper skill studente ---");
        List<IStudentSkill> mappedStudentSkills = studentSkills.stream()
                .map(StudentSkillMapper::toModel)
                .toList();
        mappedStudentSkills.forEach(s ->
                System.out.println("  Skill mappata: " + s.getName() + " | PreparazioneRichiesta: " + s.getPreparationRequired())
        );

        System.out.println("\n--- 7. Mapper nemici con skill random ---");
        List<IBossSkill> mappedBossSkills = bossSkills.stream()
                .map(BossSkillMapper::toModel)
                .toList();
        enemies.forEach(e -> {
            // assegna skill random al nemico
            List<BossSkillEntity> randomSkills = bossSkills.stream()
                    .filter(s -> Math.random() > 0.5)
                    .limit(3)
                    .toList();
            e.setSkills(randomSkills);
            Enemy enemy = EnemyMapper.toModel(e);
            System.out.println("  Nemico: " + enemy.getName() +
                    " | Skill assegnate: " + enemy.getSkills().size());
        });

        System.out.println("\n--- 8. Mapper stanze ---");
        rooms.forEach(r -> {
            IRoom room = RoomMapper.toModel(r);
            System.out.println("  Stanza mappata: " + room.getName() +
                    " | Tipo: " + room.getClass().getSimpleName() +
                    " | Uscite: " + room.getExits().size());
        });

        // ── 3. TEST SALVATAGGIO STUDENTE ──────────────────────

        System.out.println("\n--- 9. Creazione e salvataggio studente ---");
        Student student = new Student(
                "TestStudente",
                100,
                new Level(),
                50,
                50,
                100,
                mappedStudentSkills,
                new Inventory(100, new HashMap<>())
        );

        StudentEntity studentEntity = StudentMapper.toEntity(student);
        StudentStore studentStore = new StudentStore();
        studentStore.save(studentEntity);
        System.out.println("  Studente salvato: " + studentEntity.getName());

        // ── 4. TEST CARICAMENTO STUDENTE ──────────────────────

        System.out.println("\n--- 10. Caricamento studente dal DB ---");
        StudentEntity loadedEntity = studentStore.findById(studentEntity.getId());
        IStudent<IStudentSkill> loadedStudent = StudentMapper.toModel(loadedEntity);
        System.out.println("  Studente caricato: " + loadedStudent.getName() +
                " | HP: " + loadedStudent.getLife() +
                " | Monete: " + loadedStudent.getInventory().seeCoins() +
                " | Skill: " + loadedStudent.getSkills().size());

        // ── 5. TEST AGGIORNAMENTO STUDENTE ────────────────────

        System.out.println("\n--- 11. Aggiornamento studente ---");
        loadedEntity.setLife(80);
        studentStore.update(loadedEntity);
        StudentEntity updatedEntity = studentStore.findByName("TestStudente");
        System.out.println("  HP aggiornati: " + updatedEntity.getLife());

        // ── 5. TEST AGGIUNTA LIBRO STUDENTE ────────────────────

        System.out.println("\n--- 12. Aggiunta libro studente ---");

        StudentEntity ldStudent = studentStore.findByName("TestStudente");
        IStudent<IStudentSkill> studentModel = StudentMapper.toModel(ldStudent);
        System.out.println("  Libri dello studente: " + studentModel.getInventory().getItems().size());
        IItem book = ItemMapper.toModel(books.getFirst());
        studentModel.getInventory().addItem(book);
        StudentMapper.updateEntity(studentModel, ldStudent);
        studentStore.update(ldStudent);
        System.out.println("  Libro aggiunto: " + studentModel.getInventory().getItems().size());

        System.out.println("\n--- 13. Aggiunta skill studente ---");

        StudentEntity ldStudentForSkill = studentStore.findByName("TestStudente");
        IStudent<IStudentSkill> studentModelForSkill = StudentMapper.toModel(ldStudentForSkill);
        System.out.println("  Skill attuali dello studente: " + studentModelForSkill.getSkills().size());

        IStudentSkill newSkill = StudentSkillMapper.toModel(studentSkills.getFirst());
        studentModelForSkill.addSkill(newSkill);

        StudentMapper.updateEntity(studentModelForSkill, ldStudentForSkill);
        studentStore.update(ldStudentForSkill);

        IStudent<IStudentSkill> studentModelVerify = StudentMapper.toModel(ldStudentForSkill);
        System.out.println("  Skill dopo l'aggiunta: " + studentModelVerify.getSkills().size());

        System.out.println("\n=== TEST SKILL COMPLETATO ===");
    }
}
